merchex/urls.py
from django.contrib import admin
from django.urls import path

from liste import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.hello, name='hello'),
    path('about-us/', views.about, name='about-us'),
    path('bands/', views.band_list),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/',views.band_list, name='band-list'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),

    path('annonces/', views.annonce_list),
    path('annonces/<int:id>/', views.annonce_det, name='annonce-det'),
    path('annonces/',views.annonce_list, name='annonce-list'),
    path('annoncec/add/', views.annonce_create, name='annonce-create'),
    path('annonces/<int:id>/change/', views.annonce_update, name='annonce-update'),
    path('annonces/<int:id>/delete/', views.annonce_delete, name='annonce-delete'),

    path('contact-us/',views.contact, name='contact'),
    path('confirmation/', views.confirmation, name='confirmation'),
]

liste/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator



class Band(models.Model):
    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(max_length=50)
    biography = models.fields.CharField(max_length=100)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
        )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
    
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)

    # like_new = models.fields.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'

class Annonce(models.Model):
    titre = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=100)
    sold = models.fields.BooleanField(default=True)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
        )
    type = models.fields.CharField(max_length=50)
    official_homepage = models.fields.URLField(null=True, blank=True)

    class Type(models.TextChoices):
        DISQUES = 'D'
        VETEMENTS = 'V'
        AFFICHE = 'A'
        DIVERS ='DI'

    
    type = models.fields.CharField(choices=Type.choices, max_length=20)

    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)


    def __str__(self):
        return f'{self.titre}'

liste/forms.py
from django import forms
from liste.models import Band, Annonce


class ContactUsForm(forms.Form):
    Nom = forms.CharField(required=False)
    email = forms.CharField()
    message = forms.CharField(max_length=1000)

# Laissez votre modèle définir la forme
# class BandForm(forms.Form):
#    name = forms.CharField(max_length=100)
#    biography = forms.CharField(max_length=1000)
#    year_formed = forms.IntegerField(min_value=1900, max_value=2021)
#    official_homepage = forms.URLField(required=False)

class BandForm(forms.ModelForm): #Générez automatiquement un formulaire à partir d'un modèle avec un ModelForm
   class Meta:
     model = Band
    #  fields = '__all__'
     exclude = ('active', 'official_homepage') 


class AnnonceForm(forms.ModelForm):
   class Meta:
     model = Annonce
     fields = '__all__'

liste/views.py
from django.http import HttpResponse
from django.shortcuts import render
from liste.models import Band, Annonce
from liste.forms import ContactUsForm, BandForm, AnnonceForm
from django.core.mail import send_mail
from django.shortcuts import redirect  # ajoutez cet import



def hello(request):
    bands = Band.objects.all()
    return render(request, 
                'liste/hello.html',
                {'bands' : bands} )

def about(request):
    return render(request,
                        'liste/about.html',)


def band_list(request):  # renommer la fonction de vue
   bands = Band.objects.all()
   return render(request,
           'liste/band_list.html',  # pointe vers le nouveau nom de modèle
           {'bands': bands})

def band_detail(request, id):
  band = Band.objects.get(id=id)  # nous insérons cette ligne pour obtenir le Band avec cet id
  return render(request,
          'liste/band_detail.html',
          {'band': band}) # nous mettons à jour cette ligne pour passer le groupe au gabarit

def annonce_list(request): 
   annonces = Annonce.objects.all()
   return render(request,
           'liste/annonce_list.html',
           {'annonces': annonces})

def annonce_det(request, id):
  annonce = Annonce.objects.get(id=id)
  return render(request,
          'liste/annonce_det.html',
          {'annonce': annonce})


def contact(request):
    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["Nom"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['shileiwei200@gmail.com'],
            )
            # Rediriger vers une page de remerciement ou afficher un message de succès
            return redirect('confirmation')  # remplacez 'confirmation' par l'URL appropriée
    else:
        # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()

    return render(request, 'liste/contact.html', {'form': form})

def confirmation(request):
    return render(request, 'liste/confirmation.html')


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('band-detail', band.id)

    else:
        form = BandForm()

    return render(request,
            'liste/band_create.html',
            {'form': form})

def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                'liste/band_update.html',
                {'form': form})


def band_delete(request, id):
    band = Band.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'liste/band_delete.html',
                    {'band': band})



def annonce_create(request):
    if request.method == 'POST':
        form = AnnonceForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            annonce = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('annonce-det', annonce.id)

    else:
        form = AnnonceForm()

    return render(request,
            'liste/annonce_create.html',
            {'form': form})


def annonce_update(request, id):
    annonce = Annonce.objects.get(id=id)

    if request.method == 'POST':
        form = AnnonceForm(request.POST, instance=annonce)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('annonce-det', annonce.id)
    else:
        form = AnnonceForm(instance=annonce)

    return render(request,
                'liste/annonce_update.html',
                {'form': form})

def annonce_delete(request, id):
    annonce = Annonce.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        annonce.delete()
        # rediriger vers la liste des groupes
        return redirect('annonce-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'liste/annonce_delete.html',
                    {'annonce': annonce})

liste/templates/liste/about.html
{% extends 'liste/base.html' %}

{% block content %}

<h1>À propos de nous</h1>
<p>..........................................</p>

{% endblock %}

liste/templates/liste/annonce_create.html
 <h1>Créer un nouveau annonce</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

liste/templates/liste/annonce_delete.html
{% extends 'liste/base.html' %}

{% block content %}
<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ annonce.titre }} ?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Supprimer">
</form>

{% endblock %}

liste/templates/liste/annonce_det.html
{% extends 'liste/base.html' %}

{% block content %}

<h2>{{ annonce.titre }}</h2>

<ul>
    <li>Type : {{ annonce.type }}</li>
    <li>Année : {{ annonce.year }}</li>
    <li>Sold : {{ annonce.sold|yesno }}</li>
   {% if annonce.official_homepage %}
   <li><a href="{{ annonce.official_homepage }}">{{ annonce.official_homepage }}</a></li>
   {% endif %}
</ul>

<p>Description : {{ annonce.description }}</p>

<div>
    <a href="{% url 'annonce-update' annonce.id %}">Modifier</a>
</div>
<div>
    <a href="{% url 'annonce-delete' annonce.id %}">Supprimer cette annonce</a>
</div>
<div>
    <a href="{% url 'annonce-list' %}">Retour à tous les Annonces</a>
</div>


{% endblock %}

liste/templates/liste/annonce_list.html
{% extends 'liste/base.html' %}

{% block content %}

<h1>Annonce</h1>

<ul>
    {% for annonce in annonces %}
    <li><a href="{% url 'annonce-det' annonce.id %}">{{ annonce.titre }}</a></li>
  {% endfor %}
</ul>
<a href="{% url 'annonce-create' %}">Créer une nouvelle annonce</a>

{% endblock %}

liste/templates/liste/annonce_update.html
{% extends 'liste/base.html' %}

{% block content %}

<h1>Mise à jour de l'annonce</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>

 {% endblock %}

liste/templates/liste/band_create.html
 <h1>Créer un nouveau groupe</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

liste/templates/liste/band_delete.html
{% extends 'liste/base.html' %}

{% block content %}

  <h1>Supprimer le groupe</h1>

  <p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>

{% endblock %}

liste/templates/liste/band_detail.html
{% extends 'liste/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno }}</li>
   {% if band.official_homepage %}
   <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
   {% endif %}
</ul>

<p>Biographie : {{ band.biography }}</p>

<div>
    <a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>
</div>

<div>
    <a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>
</div>

<div>
    <a href="{% url 'band-list' %}">Retour à tous les groupes</a>
</div>


{% endblock %}

liste/templates/liste/band_list.html
{% extends 'liste/base.html' %}

{% block content %}

<h1>Groupes</h1>

<ul>
    {% for band in bands %}
    <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a></li>
  {% endfor %}
</ul>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

{% endblock %}

liste/templates/liste/band_update.html
{% extends 'liste/base.html' %}

{% block content %}

<h1>Mise à jour du groupe</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>

 {% endblock %}

liste/templates/liste/base.html
{% load static %}

<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'liste/style.css' %}" />
    
    </head>

    <body>

        <nav>
          <a href="{% url 'hello' %}">Accueil</a>
          <a href="{% url 'band-list' %}">Groupes</a>
          <a href="{% url 'annonce-list' %}">Annonces</a>
          <a href="{% url 'about-us' %}">A propos de nous</a>
          <a href="{% url 'contact' %}">Contactez-nous</a>
        </nav>
     
        {% block content %}{% endblock %}
     
    </body>

</html>

liste/templates/liste/contact.html
{% load static %}

<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Page de Contact</title>
        <link rel="stylesheet" href="{% static 'liste/contact.css' %}">
    </head>
<body>
    <nav>
        <a href="{% url 'band-list' %}">Groupes</a>
        <a href="{% url 'annonce-list' %}">Annonces</a>
        <a href="{% url 'about-us' %}">A propos de nous</a>
      </nav>

    <div class="contact-container">
        <p class="help-text">Nous sommes là pour vous aider.</p>
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Envoyer" class="submit-btn">
        </form>
    </div>
</body>
</html>

liste/templates/liste/hello.html
{% extends 'liste/base.html' %}

{% block content %}

<h1>Django débutant</h1>

<p>Compétences maîtrisées :</p>
<ul>
    <li>Poser les bases d’une application Django en utilisant des modèles, des vues et des gabarits.</li>
    <li>Gérer des données stockées dans une base de données à l'aide du site d'administration de Django.</li>
    <li>Construire une interface CRUD dans Django.</li>
</ul>

{% endblock %}